[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@ensdomains/buffer/=lib/buffer"]
fs_permissions = [{access = "read", path = "./script/premint/"}]
evm_version = "london"

[rpc_endpoints]
sepolia="${SEPOLIA_RPC_URL}"
crab="${DARWINIA_CRAB_RPC_URL}"

[etherscan]
sepolia={url = "https://eth-sepolia.blockscout.com/api", key = "", chain = 11155111 }
crab={url = "https://crab-scan.darwinia.network/api", key = "", chain = 44 }