[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@ensdomains/buffer/=lib/buffer"]
fs_permissions = [{access = "read", path = "./script/premint/"}]
evm_version = "london"

[rpc_endpoints]
l1="${L1_RPC_URL}"
l2="${L2_RPC_URL}"

[etherscan]
l1={url = "${L1_SCAN_API_URL}", key = "${L1_SCAN_API_KEY}", chain = 1 }
l2={url = "${L2_SCAN_API_URL}", key = "${L2_SCAN_API_KEY}", chain = 46 }
