[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@ensdomains/buffer/=lib/buffer"]
fs_permissions = [{access = "read", path = "./script/premint/"}]
evm_version = "london"

[rpc_endpoints]
sepolia="${SEPOLIA_RPC_URL}"
koi="${DARWINIA_KOI_RPC_URL}"

[etherscan]
sepolia={url = "https://api-sepolia.etherscan.io/api", key = "${ETHERSCAN_API_KEY}"}
koi={url = "https://koi-scan.darwinia.network/api", key = "", chain = 701 }
